### ISSUE TITLE
No css on OMERO.web

### ISSUE THREAD

**Issue by pwalczysko** [ome/ansible-example-omero-onenode#13]
When I build this example inside a docker with a Dockerfile like

```
FROM centos/systemd

CMD ["/sbin/init"] 
```

With a command
``docker build -f Dockerfile.j2 --rm --no-cache -t httpd .``
Then run it with:
``docker run --privileged --name httpd  -p 22 -p 4063:4063 -p 4064:4064 -p 4080:4080 -p 8080:80  -d  httpd``
Then start a bash session inside the docker 
``docker exec -it httpd bash``

Inside the docker run
```
yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute ca-certificates && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all
LC_CTYPE=en_US.UTF-8
export LC_CTYPE
yum install --assumeyes python3-pip
pip3 install --upgrade pip
pip install ansible
```

Then, copy the three crucial files from this repo, ``playbook.yml``, ``requirements.yml`` and ``hosts.yml`` to the docker env.
Change the host in the ``hosts.yml`` to ``localhost``.

Inside the docker, run
```
ansible-galaxy install -r requirements.yml
ansible-playbook --become --connection=local -i hosts.yml playbook.yml
```

This results in a successful run of the playbook, and then outside of the docker, I can connect successfully using CLI and OMERO.insight connecting to ``localhost`` and the OMERO works fine, except the [SSL handshake problem](https://github.com/ome/ansible-example-omero-onenode/issues/14) in CLI during import only (OMERO.insight imports without a problem).

Nevertheless, 

Issues:
1. When setup done as above, OMERO.web cannot be accessed on ``http://localhost:4080/webclient`` - FF reports that "connection was reset".
2. When inside the docker a config line is added ``omero config set omero.web.application_server.host 0.0.0.0`` and omero web is restarted, then OMERO.web can be accessed on ``http://localhost:4080/webclient``- but the css is missing, see screenshot below. (note that you can successfully login into such strangely formatted OMERO.web login page, but of course further work is blocked after login by misformatting).

![Screenshot 2022-08-26 at 10 53 31](https://user-images.githubusercontent.com/2478303/186878678-2cad9782-ecd7-4168-acf4-389f0fb0f137.png)

My opinion would be that 
1. the config line ``omero config set omero.web.application_server.host 0.0.0.0`` should be added to the [playbook.yml](https://github.com/ome/ansible-example-omero-onenode/blob/master/playbook.yml).
2. But the fact that this does not sort out the css problem in Issues Ad 2. above, makes me think that maybe I am not getting this completely right.
3. It might be that I am hitting something like https://stackoverflow.com/questions/10075304/nginx-fails-to-load-css-files - but this is beyond my depth to judge.

cc @sbesson @will-moore

**Comment by pwalczysko** [comment]
One idea:

Many playbooks in https://github.com/ome/prod-playbooks have nginx capped at 1.18.0, such as https://github.com/ome/prod-playbooks/blob/3b3d2e0f2f1f048b2219c9094d7bef8cb43ae6fc/web-proxy/playbook.yml#L32.
But in my workflow, I am having nginx 1.22.x.
I suppose that the capping is done in a variable which is used by the role ome.nginx ?

**Comment by pwalczysko** [comment]
In the OMEROweb.log I can see 

```
2022-09-02 14:47:27,692 WARNI [                          django.request] (proc.06290) log_response():230 HTTP 404 <WSGIRequest: GET '/static/webclient/image/custom_login_logo.png'>
```

I think that this is the reason that these css and other static files are not served and I cannot see them in the webclient login page. I tried to

1. compare the permissions on the folders such as ``/static/webclient/image/`` - the ``/static`` folder actually did not exist, but this is in line with the functioning ``outreach`` server
2. I created the ``/static/webclient/image/`` and other folders by hand and copy the files from ``/opt/omero/web/OMERO.web/var/static/`` to the newly manually created ``/static`` and restart nginx and OMERO.web, and it did not help (still no css on login page)
3. I compared the perms on the ``/opt/omero/web/OMERO.web/var/static/`` folders in comparison with ``outreach`` -> no differences detected

**Comment by joshmoore** [comment]
Is this related to @jburel's recent whitenoise PR?

**Comment by jburel** [comment]
this is more likely to be related to a omero.web configuration. something like ``omero config set omero.web.debug True`` might help

**Comment by pwalczysko** [comment]
Thanks a lot @jburel , this fixed it.
I tested it yesterday manually fixing the config and the css appeared as expected.
I am now working on the full workflow using ansible, and will open a PR fixing the playbook.

**Comment by pwalczysko** [comment]
@will-moore Strangely, I was able to go over the ``docker run...`` step on my M1 machine successfully (I was successful already previously on the MacBookPro).
Do you want to try some solutions from https://stackoverflow.com/questions/66662820/m1-docker-preview-and-keycloak-images-platform-linux-amd64-does-not-match-th ?
The ``docker build -t <image-name> --platform linux/x86_64`` which you would add to the previous ``build`` command seems low cost to try and fairly logical to me ?

**Comment by will-moore** [comment]
Tried:

```
$ docker build -f Dockerfile.j2 --rm --no-cache -t httpd --platform linux/x86_64 .

$ docker run --privileged --name httpd -p 22 -p 4063:4063 -p 4064:4064 -p 4080:4080 -p 8080:80 -d httpd
docker: Error response from daemon: Conflict. The container name "/httpd" is already in use by container...

$ docker run --privileged --name httpd2 -p 22 -p 4063:4063 -p 4064:4064 -p 4080:4080 -p 8080:80 -d httpd
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
d1c2aa3a1eaf81d5e2703fbf1f0607c5da44efbd954c7647a17792469719d1ad

$ docker exec -it httpd2 bash
[root@d1c2aa3a1eaf /]#

# followed all the steps in description above...

...until...

[root@d1c2aa3a1eaf /]# ansible-playbook --become --connection=local -i hosts.yml playbook.yml
...
TASK [ome.postgresql : postgres | initialise PostgreSQL cluster (skip if data directory already exists)] ******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/pgsql-13/bin/postgresql-13-setup", "initdb"], "delta": "0:00:00.514084", "end": "2022-11-04 10:06:09.047965", "msg": "non-zero return code", "rc": 1, "start": "2022-11-04 10:06:08.533881", "stderr": "Failed to get D-Bus connection: No such file or directory", "stderr_lines": ["Failed to get D-Bus connection: No such file or directory"], "stdout": "failed to find PGDATA setting in postgresql-13.service", "stdout_lines": ["failed to find PGDATA setting in postgresql-13.service"]}

PLAY RECAP ****************************************************************************************************************************************
localhost                  : ok=8    changed=5    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0   
```
