### ISSUE TITLE
systemd problem

### ISSUE THREAD

**Issue by pwalczysko** [ome/ansible-example-omero-onenode#17]
Following the workflow

Dockerfile:
```
FROM centos/systemd
RUN yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute ca-certificates && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;

CMD ["/sbin/init"]
```

then
```
docker build -f Dockerfile.j2 --rm --no-cache -t omero .
docker run --privileged --name omero -v /Users/pwalczysko/omero/:/OMERO  -p 22 -p 4063:4063 -p 4064:4064 -p 4080:4080 -p 8080:80 -d omero
docker exec -it omero bash
```

The, from inside the container 

```
[root@2dade2873d73 /]# LC_CTYPE=en_US.UTF-8
[root@2dade2873d73 /]# export LC_CTYPE
[root@2dade2873d73 /]# yum install --assumeyes python3-pip
[root@2dade2873d73 /]# ansible-playbook --become --connection=local -i hosts.yml playbook.yml
[root@2dade2873d73 /]# pip3 install --upgrade pip
[root@2dade2873d73 /]# pip install ansible
[root@2dade2873d73 dbs]# ansible-galaxy install -r requirements.yml
[root@2dade2873d73 dbs]# ansible-playbook --become --connection=local -i hosts.yml playbook.yml
....
....

TASK [ome.postgresql : postgres | initialise PostgreSQL cluster (skip if data directory already exists)] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/pgsql-13/bin/postgresql-13-setup", "initdb"], "delta": "0:00:00.515375", "end": "2022-12-12 16:45:53.541899", "msg": "non-zero return code", "rc": 1, "start": "2022-12-12 16:45:53.026524", "stderr": "Failed to get D-Bus connection: No such file or directory", "stderr_lines": ["Failed to get D-Bus connection: No such file or directory"], "stdout": "failed to find PGDATA setting in postgresql-13.service", "stdout_lines": ["failed to find PGDATA setting in postgresql-13.service"]}

PLAY RECAP *********************************************************************
localhost                  :
```

I am trying to set up something similar as in the molecule tests of this repo.
The failure is probably connected with systemd, such as https://stackoverflow.com/questions/28495341/start-a-service-in-docker-container-failed-with-error-failed-to-get-d-bus-conne or https://stackoverflow.com/questions/50393525/failed-to-get-d-bus-connection-operation-not-permitted.
This used to work couple of months ago, but something changed in between. 
Any ideas @sbesson please ? Do the tests in https://github.com/ome/ansible-example-omero-onenode/blob/master/molecule/resources/Dockerfile.j2 work (not sure how to trigger them) ?

Thanks

**Comment by sbesson** [comment]
> Do the tests in https://github.com/ome/ansible-example-omero-onenode/blob/master/molecule/resources/Dockerfile.j2 work (not sure how to trigger them) ?

The cron jobs had been disabled after 60 days of inactivity. I re-enable it but if you want a run, you might be able to open a temporary PR to trigger a build.

> Any ideas @sbesson please ? 

The only immediate data point coming to mind are the issues reported in https://github.com/ome/ansible-role-postgresql/issues/27. In particular, the error message possibly brings us back to the workaround in https://github.com/ome/ansible-role-postgresql/issues/27#issuecomment-1136025964 and might suggest we want the role to set up `PG_DATA`.

**Comment by pwalczysko** [comment]
I am positive now that this is (in my hands) an M1-specific problem. I can build an image with working OMERO on MacBookPro, then push it to dockerhub, then pull this image to M1 and do

```
docker run --privileged --name omero-via-hub2 -v /Users/pwalczysko/omero/dbs:/OMERO -p 22 -p 4063:4063 -p 4064:4064 -p 4080:4080 -p 8080:80 -d pwalczysko/omero:tag2
docker exec -it omero-via-hub2 bash
[root@1d01f5827df9 /]# systemctl restart omero-server
Failed to get D-Bus connection: No such file or directory
```

Any ideas how to make this running please ? Not sure at what stage should I define 

``set up PG_DATA.``  ?

But it seems to me that the whole systemd, not just postgres is not working in the M1 env, or am I wrong here ?

**Comment by pwalczysko** [comment]
Maybe it is https://forums.docker.com/t/m1-mac-centos-7-failed-to-get-d-bus-connection-no-such-file-or-directory/132257 ?

**Comment by pwalczysko** [comment]
Solution for the systemd problem was:

```
cat ~/Library/Group\ Containers/group.com.docker/settings.json| grep deprecatedC
  "deprecatedCgroupv1": false,
vi ~/Library/Group\ Containers/group.com.docker/settings.json # To change the value to true
cat ~/Library/Group\ Containers/group.com.docker/settings.json| grep deprecatedC
  "deprecatedCgroupv1": true,

#Restart your Docker
```

Further workflow - @will-moore you can use my prebuilt docker image, which you get as follows:

```
docker pull pwalczysko/omero:tag2 # takes minutes, some 2.5GB to download
docker images #lists all the images, one of which should be pwalczysko/omero:tag2
docker run --privileged --name omero-via-hub -p 22 -p 4063:4063 -p 4064:4064 -p 4080:4080 -p 8080:80 -d pwalczysko/omero:tag2
docker exec -it omero-via-hub bash 
systemctl restart omero-server # Maybe not necessay, depending on how you fare with the OMERO.web check below
```

Go to 
http://localhost:8080/webclient/

Log in as
root
$PASSWORD # will deliver privately

**Comment by pwalczysko** [comment]
Thanks @sbesson , I am closing the issue as it is solved for me

**Comment by jburel** [comment]
@will-moore could that be a solution for you so you can have a local server?

**Comment by will-moore** [comment]
```
$ docker run --privileged --name omero-via-hub -p 22 -p 4063:4063 -p 4064:4064 -p 8080:80 -d pwalczysko/omero:tag2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
41771eaeecb4f1feb9fea9431bed24884e6bb6c3b2b53a9f9f8347d01ba747a1

$ docker exec -it omero-via-hub bash 
[root@41771eaeecb4 /]# systemctl restart omero-server
Failed to get D-Bus connection: No such file or directory
```

**Comment by pwalczysko** [comment]
> Failed to get D-Bus connection: No such file or directory

Yes, this is why I opened this issue in the first place - @will-moore though was able to sort it out via restarting the Docker (going via the icon of the Docker icon in the M1's top left toolbar and selecting "Restart"

**Comment by will-moore** [comment]
Wow, it's working!!! 👍  - I'd simply failed to restart Docker properly.
I can log-in and import images etc! 👍
